name: Java 21 Compatibility

on:
  push:
    branches: [ main ]
    branches-ignore:
      - release/*
  pull_request:
    branches: [ main ]
    branches-ignore:
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build (Java 21)
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Build all modules
        run: ./gradlew build --stacktrace -x test