name: Deploy Combined Javadoc

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Generate Combined Javadoc
        run: |
          ./gradlew clean aggregateJavadocs
          mkdir _site
          cp -r build/docs/javadoc/* _site/

      - name: Disable Jekyll
        run: touch ./_site/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e
        with:
          publish_dir: ./_site
          publish_branch: gh-pages