name: Sonar Cloud Library
on:
  push:
    branches:
      - main
    branches-ignore:
      - release/*

jobs:
  sonarcloud:
    name: Sonar Cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build, Coverage, Analyze
        run: ./gradlew clean test jacocoTestReport sonar --info
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          SONAR_TOKEN:  ${{ secrets.SONAR_TOKEN }}